[package]
name = "marvin"
version = "0.1.0"
authors = ["MJohnson459 <mjohnson459@gmail.com>"]

[dependencies]
diesel = {version = "1.1.1", features = ["postgres"]}
dotenv = "0.10.1"

serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
