[package]
name = "marvin_server"
version = "0.1.0"
authors = ["Michael Johnson <mjohnson459@gmail.com>"]
edition = "2018"

[dependencies]
marvin_core = { path = "../marvin_core" }
ros_parser = { path = "../ros_parser" }

url = "1.7.2"
rocket = "0.4.0"
